### ISSUE TITLE
I want To Join This Organization.

### ISSUE THREAD

**Issue by JayantGoel001** [PHPMap/laravel-slack-invite#2]
@JayantGoel001
jgoel92@gmail.com

**Comment by fwartner** [comment]
Added you :)

**Comment by JayantGoel001** [comment]
> Added you :)

Link you send is not working 😢

**Comment by fwartner** [comment]
The link came from GitHub itself. Do you want to join the slack? This isn't active anymore.

**Comment by JayantGoel001** [comment]
Actually i wanted to join the organisation
